services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  flask:
    build: .
    ports:
      - 5000:5000
    environment:
      DATABASE: postgresql+psycopg
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    env_file:
      - .env
    command: bash -c "waitress-serve --host 0.0.0.0 --port 5000 --call app:create_app"
volumes:
  postgres:
