on:
  push:
    branches: ["master"]



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up python
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.5"
    - name: install dependecies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-cache --no-root --no-directory --with dev --without postgres
    - name: pytest and coverage
      run: |
        pytest -n auto --cov=app